import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {Header} from './components/header.mjs';import {Hero} from './components/hero.mjs';import {History} from './components/history.mjs';import {Ecosystem} from './components/ecosystem.mjs';import {Products,products} from './components/products.mjs';import {Differentials} from './components/differentials.mjs';import {Vision} from './components/vision.mjs';import {Contact} from './components/contact.mjs';import {Footer} from './components/footer.mjs';import {logo,label,button} from './components/shared.mjs';
const title='Nefriva | Tecnologia Renal para uma Vida Melhor';
const description='A Nefriva é um ecossistema de tecnologia renal que desenvolve soluções digitais para transformar a jornada de pessoas com doenças renais.';
const document=(content,pageTitle=title,desc=description)=>`<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#075b62"><title>${pageTitle}</title><meta name="description" content="${desc}"><meta property="og:title" content="${pageTitle}"><meta property="og:description" content="${desc}"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Nefriva"><link rel="icon" href="/assets/nefriva.jpeg" type="image/jpeg"><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/main.js" defer></script></head><body>${Header()}<main id="conteudo">${content}</main>${Footer()}</body></html>`;
await writeFile('dist/index.html',document(Hero()+History()+Ecosystem()+Products()+Differentials()+Vision()+Contact()));
for(const p of products){await mkdir('dist/'+p.slug,{recursive:true});const slotText=p.slug==='minha-dialise'?'Duas modalidades. Uma rotina mais organizada.':'Informação alimentar com câmera e realidade aumentada.';const healthNote=p.slug==='minha-dialise'?'Minha Diálise apoia a organização e o acesso às informações do tratamento. Não substitui a orientação da equipe de saúde.':'Renal Food apoia o acesso a informações alimentares e escolhas mais conscientes. Não substitui a orientação individual da equipe de saúde e nutrição.';await writeFile('dist/'+p.slug+'/index.html',document(`<section class="section product-detail"><div class="container"><a class="back-link" href="/#produtos">← Voltar ao ecossistema</a><div class="detail-grid"><div>${label('UM PRODUTO DO ECOSSISTEMA NEFRIVA')}<h1>${p.name}</h1><p class="lead">${p.description}</p><p>${p.detail}</p><p class="detail-status">${p.status}</p><p>${p.note}</p>${button('Fale com a Nefriva','/#contato')}</div><div class="detail-logo">${logo(p.slug,'',true)}</div></div><div class="screenshot-slot" data-screenshot-slot="${p.slug}"><p>${slotText}</p><span>${p.features.join(' · ')}</span></div><p class="health-note">${healthNote}</p></div></section>`,p.name+' | Nefriva',p.description));}
await writeFile('dist/404.html',document(`<section class="section"><div class="container"><h1>Página não encontrada.</h1><p>Continue conhecendo o ecossistema Nefriva.</p>${button('Voltar ao início','/')}</div></section>`,'Página não encontrada | Nefriva'));
console.log('Generated landing page, two product pages and 404.');
